2018-03-13-2127-3e6472e|PBLEID-15899: Pollejobber forsvinner sporløst

diff --git a/docker/run-local b/docker/run-local
--- a/docker/run-local
+++ b/docker/run-local
@@ -1,10 +1,26 @@
 #!/usr/bin/env bash
 
+checkLabel() {
+    local label=$1
+    local nodeId=$2
+    value=$(docker node inspect ${nodeId} | jq ".[].Spec.Labels.\"${label}\"") || { echo "Failed to inspect node"; return 1; }
+    [[ 'null' == ${value} ]] && {
+        read -p "Node label '${label}' not set. Set it? [Y/n] " answer
+        [[ -z ${answer} ]] && answer='y'
+        [[ ${answer} =~ [yY] ]] && { docker node update ${nodeId} --label-add ${label}=true; } || { echo "Failed to create label"; return 1; }
+    } || return 0
+}
+
 docker node ls 2>&1 >/dev/null || {
     read -p "Enable swarm mode in Docker? [Y/n] " answer
     [[ -z ${answer} ]] && answer='y'
     [[ ${answer} =~ [yY] ]] && { docker swarm init; } || { exit 1; }
 }
+
+nodeId=$(docker node inspect self | jq -r ".[].ID") || exit 1
+checkLabel jenkins-slave ${nodeId} || exit 1
+checkLabel jenkins-master ${nodeId} || exit 1
+checkLabel nexus ${nodeId} || exit 1
 
 [[ -z $(docker secret ls -q) ]] && {
     read -p "No secrets found in Docker's vault. Create dummy secrets? [Y/n] " answer
